from sqlmodel import Session

from app.models import Word


WORDS_DATA = [
    {"polish": "ja", "english": "I", "ukrainian": "я"},
    {"polish": "ty", "english": "you", "ukrainian": "ти"},
    {"polish": "on", "english": "he", "ukrainian": "він"},
    {"polish": "ona", "english": "she", "ukrainian": "вона"},
    {"polish": "my", "english": "we", "ukrainian": "ми"},
    {"polish": "wy", "english": "you (plural)", "ukrainian": "ви"},
    {"polish": "oni", "english": "they", "ukrainian": "вони"},
    {"polish": "to", "english": "this/it", "ukrainian": "це"},
    {"polish": "jest", "english": "is", "ukrainian": "є"},
    {"polish": "nie", "english": "no/not", "ukrainian": "не"},
    {"polish": "tak", "english": "yes", "ukrainian": "так"},
    {"polish": "co", "english": "what", "ukrainian": "що"},
    {"polish": "kto", "english": "who", "ukrainian": "хто"},
    {"polish": "gdzie", "english": "where", "ukrainian": "де"},
    {"polish": "kiedy", "english": "when", "ukrainian": "коли"},
    {"polish": "dlaczego", "english": "why", "ukrainian": "чому"},
    {"polish": "jak", "english": "how", "ukrainian": "як"},
    {"polish": "który", "english": "which", "ukrainian": "який"},
    {"polish": "czy", "english": "whether/if", "ukrainian": "чи"},
    {"polish": "dom", "english": "house", "ukrainian": "дім"},
    {"polish": "rodzina", "english": "family", "ukrainian": "сім'я"},
    {"polish": "przyjaciel", "english": "friend", "ukrainian": "друг"},
    {"polish": "dzień", "english": "day", "ukrainian": "день"},
    {"polish": "noc", "english": "night", "ukrainian": "ніч"},
    {"polish": "czas", "english": "time", "ukrainian": "час"},
    {"polish": "życie", "english": "life", "ukrainian": "життя"},
    {"polish": "człowiek", "english": "person", "ukrainian": "людина"},
    {"polish": "praca", "english": "work", "ukrainian": "робота"},
    {"polish": "szkoła", "english": "school", "ukrainian": "школа"},
    {"polish": "język", "english": "language", "ukrainian": "мова"},
    {"polish": "miasto", "english": "city", "ukrainian": "місто"},
    {"polish": "kraj", "english": "country", "ukrainian": "країна"},
    {"polish": "droga", "english": "road", "ukrainian": "дорога"},
    {"polish": "samochód", "english": "car", "ukrainian": "автомобіль"},
    {"polish": "pociąg", "english": "train", "ukrainian": "поїзд"},
    {"polish": "autobus", "english": "bus", "ukrainian": "автобус"},
    {"polish": "sklep", "english": "shop", "ukrainian": "магазин"},
    {"polish": "jedzenie", "english": "food", "ukrainian": "їжа"},
    {"polish": "woda", "english": "water", "ukrainian": "вода"},
    {"polish": "chleb", "english": "bread", "ukrainian": "хліб"},
    {"polish": "ser", "english": "cheese", "ukrainian": "сир"},
    {"polish": "mleko", "english": "milk", "ukrainian": "молоко"},
    {"polish": "kawa", "english": "coffee", "ukrainian": "кава"},
    {"polish": "herbata", "english": "tea", "ukrainian": "чай"},
    {"polish": "owoc", "english": "fruit", "ukrainian": "фрукт"},
    {"polish": "jabłko", "english": "apple", "ukrainian": "яблуко"},
    {"polish": "banan", "english": "banana", "ukrainian": "банан"},
    {"polish": "pomarańcza", "english": "orange", "ukrainian": "апельсин"},
    {"polish": "warzywo", "english": "vegetable", "ukrainian": "овоч"},
    {"polish": "ziemniak", "english": "potato", "ukrainian": "картопля"},
    {"polish": "marchewka", "english": "carrot", "ukrainian": "морква"},
    {"polish": "lody", "english": "ice cream", "ukrainian": "морозиво"},
    {"polish": "cukier", "english": "sugar", "ukrainian": "цукор"},
    {"polish": "sól", "english": "salt", "ukrainian": "сіль"},
    {"polish": "pieprz", "english": "pepper", "ukrainian": "перець"},
    {"polish": "mięso", "english": "meat", "ukrainian": "м'ясо"},
    {"polish": "ryba", "english": "fish", "ukrainian": "риба"},
    {"polish": "jajko", "english": "egg", "ukrainian": "яйце"},
    {"polish": "dziecko", "english": "child", "ukrainian": "дитина"},
    {"polish": "kobieta", "english": "woman", "ukrainian": "жінка"},
    {"polish": "mężczyzna", "english": "man", "ukrainian": "чоловік"},
    {"polish": "chłopiec", "english": "boy", "ukrainian": "хлопчик"},
    {"polish": "dziewczynka", "english": "girl", "ukrainian": "дівчинка"},
    {"polish": "matka", "english": "mother", "ukrainian": "мати"},
    {"polish": "ojciec", "english": "father", "ukrainian": "батько"},
    {"polish": "brat", "english": "brother", "ukrainian": "брат"},
    {"polish": "siostra", "english": "sister", "ukrainian": "сестра"},
    {"polish": "miłość", "english": "love", "ukrainian": "любов"},
    {"polish": "przyroda", "english": "nature", "ukrainian": "природа"},
    {"polish": "słońce", "english": "sun", "ukrainian": "сонце"},
    {"polish": "księżyc", "english": "moon", "ukrainian": "місяць"},
    {"polish": "gwiazda", "english": "star", "ukrainian": "зірка"},
    {"polish": "niebo", "english": "sky", "ukrainian": "небо"},
    {"polish": "morze", "english": "sea", "ukrainian": "море"},
    {"polish": "rzeka", "english": "river", "ukrainian": "річка"},
    {"polish": "jezioro", "english": "lake", "ukrainian": "озеро"},
    {"polish": "góra", "english": "mountain", "ukrainian": "гора"},
    {"polish": "las", "english": "forest", "ukrainian": "ліс"},
    {"polish": "drzewo", "english": "tree", "ukrainian": "дерево"},
    {"polish": "kwiat", "english": "flower", "ukrainian": "квітка"},
    {"polish": "trawa", "english": "grass", "ukrainian": "трава"},
    {"polish": "planeta", "english": "planet", "ukrainian": "планета"},
    {"polish": "świat", "english": "world", "ukrainian": "світ"},
    {"polish": "książka", "english": "book", "ukrainian": "книга"},
    {"polish": "pióro", "english": "pen", "ukrainian": "ручка"},
    {"polish": "ołówek", "english": "pencil", "ukrainian": "олівець"},
    {"polish": "papier", "english": "paper", "ukrainian": "папір"},
    {"polish": "komputer", "english": "computer", "ukrainian": "комп'ютер"},
    {"polish": "telefon", "english": "phone", "ukrainian": "телефон"},
    {"polish": "ekran", "english": "screen", "ukrainian": "екран"},
    {"polish": "muzyka", "english": "music", "ukrainian": "музика"},
    {"polish": "film", "english": "film", "ukrainian": "фільм"},
    {"polish": "zdjęcie", "english": "photo", "ukrainian": "фото"},
    {"polish": "kawałek", "english": "piece", "ukrainian": "шматок"},
    {"polish": "but", "english": "shoe", "ukrainian": "черевик"},
    {"polish": "skóra", "english": "skin", "ukrainian": "шкіра"},
    {"polish": "głowa", "english": "head", "ukrainian": "голова"},
    {"polish": "serce", "english": "heart", "ukrainian": "серце"},
    {"polish": "ręka", "english": "hand", "ukrainian": "рука"},
    {"polish": "noga", "english": "leg", "ukrainian": "нога"},
]


def seed_words(session: Session) -> None:
    session.add_all([Word(**word_data) for word_data in WORDS_DATA])
    session.commit()
