from sqlmodel import Session

from app.models import Word


WORDS_DATA = [
    {"polish": "ja", "english": "I", "ukrainian": "я", "part_of_speech": "zaimek"},
    {"polish": "ty", "english": "you", "ukrainian": "ти", "part_of_speech": "zaimek"},
    {"polish": "on", "english": "he", "ukrainian": "він", "part_of_speech": "zaimek"},
    {"polish": "ona", "english": "she", "ukrainian": "вона", "part_of_speech": "zaimek"},
    {"polish": "my", "english": "we", "ukrainian": "ми", "part_of_speech": "zaimek"},
    {"polish": "wy", "english": "you (plural)", "ukrainian": "ви", "part_of_speech": "zaimek"},
    {"polish": "oni", "english": "they", "ukrainian": "вони", "part_of_speech": "zaimek"},
    {"polish": "to", "english": "this/it", "ukrainian": "це", "part_of_speech": "zaimek"},
    {"polish": "jest", "english": "is", "ukrainian": "є", "part_of_speech": "czasownik"},
    {"polish": "nie", "english": "no/not", "ukrainian": "не", "part_of_speech": "inne"},
    {"polish": "tak", "english": "yes", "ukrainian": "так", "part_of_speech": "inne"},
    {"polish": "co", "english": "what", "ukrainian": "що", "part_of_speech": "zaimek"},
    {"polish": "kto", "english": "who", "ukrainian": "хто", "part_of_speech": "zaimek"},
    {"polish": "gdzie", "english": "where", "ukrainian": "де", "part_of_speech": "przysłówek"},
    {"polish": "kiedy", "english": "when", "ukrainian": "коли", "part_of_speech": "przysłówek"},
    {"polish": "dlaczego", "english": "why", "ukrainian": "чому", "part_of_speech": "przysłówek"},
    {"polish": "jak", "english": "how", "ukrainian": "як", "part_of_speech": "przysłówek"},
    {"polish": "który", "english": "which", "ukrainian": "який", "part_of_speech": "zaimek"},
    {"polish": "czy", "english": "whether/if", "ukrainian": "чи", "part_of_speech": "inne"},
    {"polish": "dom", "english": "house", "ukrainian": "дім", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "rodzina", "english": "family", "ukrainian": "сім'я", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "przyjaciel", "english": "friend", "ukrainian": "друг", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "dzień", "english": "day", "ukrainian": "день", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "noc", "english": "night", "ukrainian": "ніч", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "czas", "english": "time", "ukrainian": "час", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "życie", "english": "life", "ukrainian": "життя", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "człowiek", "english": "person", "ukrainian": "людина", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "praca", "english": "work", "ukrainian": "робота", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "szkoła", "english": "school", "ukrainian": "школа", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "język", "english": "language", "ukrainian": "мова", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "miasto", "english": "city", "ukrainian": "місто", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "kraj", "english": "country", "ukrainian": "країна", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "droga", "english": "road", "ukrainian": "дорога", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "samochód", "english": "car", "ukrainian": "автомобіль", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "pociąg", "english": "train", "ukrainian": "поїзд", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "autobus", "english": "bus", "ukrainian": "автобус", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "sklep", "english": "shop", "ukrainian": "магазин", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "jedzenie", "english": "food", "ukrainian": "їжа", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "woda", "english": "water", "ukrainian": "вода", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "chleb", "english": "bread", "ukrainian": "хліб", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "ser", "english": "cheese", "ukrainian": "сир", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "mleko", "english": "milk", "ukrainian": "молоко", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "kawa", "english": "coffee", "ukrainian": "кава", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "herbata", "english": "tea", "ukrainian": "чай", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "owoc", "english": "fruit", "ukrainian": "фрукт", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "jabłko", "english": "apple", "ukrainian": "яблуко", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "banan", "english": "banana", "ukrainian": "банан", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "pomarańcza", "english": "orange", "ukrainian": "апельсин", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "warzywo", "english": "vegetable", "ukrainian": "овоч", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "ziemniak", "english": "potato", "ukrainian": "картопля", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "marchewka", "english": "carrot", "ukrainian": "морква", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "lody", "english": "ice cream", "ukrainian": "морозиво", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "cukier", "english": "sugar", "ukrainian": "цукор", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "sól", "english": "salt", "ukrainian": "сіль", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "pieprz", "english": "pepper", "ukrainian": "перець", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "mięso", "english": "meat", "ukrainian": "м'ясо", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "ryba", "english": "fish", "ukrainian": "риба", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "jajko", "english": "egg", "ukrainian": "яйце", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "dziecko", "english": "child", "ukrainian": "дитина", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "kobieta", "english": "woman", "ukrainian": "жінка", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "mężczyzna", "english": "man", "ukrainian": "чоловік", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "chłopiec", "english": "boy", "ukrainian": "хлопчик", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "dziewczynka", "english": "girl", "ukrainian": "дівчинка", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "matka", "english": "mother", "ukrainian": "мати", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "ojciec", "english": "father", "ukrainian": "батько", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "brat", "english": "brother", "ukrainian": "брат", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "siostra", "english": "sister", "ukrainian": "сестра", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "miłość", "english": "love", "ukrainian": "любов", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "przyroda", "english": "nature", "ukrainian": "природа", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "słońce", "english": "sun", "ukrainian": "сонце", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "księżyc", "english": "moon", "ukrainian": "місяць", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "gwiazda", "english": "star", "ukrainian": "зірка", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "niebo", "english": "sky", "ukrainian": "небо", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "morze", "english": "sea", "ukrainian": "море", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "rzeka", "english": "river", "ukrainian": "річка", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "jezioro", "english": "lake", "ukrainian": "озеро", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "góra", "english": "mountain", "ukrainian": "гора", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "las", "english": "forest", "ukrainian": "ліс", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "drzewo", "english": "tree", "ukrainian": "дерево", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "kwiat", "english": "flower", "ukrainian": "квітка", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "trawa", "english": "grass", "ukrainian": "трава", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "planeta", "english": "planet", "ukrainian": "планета", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "świat", "english": "world", "ukrainian": "світ", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "książka", "english": "book", "ukrainian": "книга", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "pióro", "english": "pen", "ukrainian": "ручка", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "ołówek", "english": "pencil", "ukrainian": "олівець", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "papier", "english": "paper", "ukrainian": "папір", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "komputer", "english": "computer", "ukrainian": "комп'ютер", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "telefon", "english": "phone", "ukrainian": "телефон", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "ekran", "english": "screen", "ukrainian": "екран", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "muzyka", "english": "music", "ukrainian": "музика", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "film", "english": "film", "ukrainian": "фільм", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "zdjęcie", "english": "photo", "ukrainian": "фото", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "kawałek", "english": "piece", "ukrainian": "шматок", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "but", "english": "shoe", "ukrainian": "черевик", "part_of_speech": "rzeczownik", "gender": "męskorzeczowy"},
    {"polish": "skóra", "english": "skin", "ukrainian": "шкіра", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "głowa", "english": "head", "ukrainian": "голова", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "serce", "english": "heart", "ukrainian": "серце", "part_of_speech": "rzeczownik", "gender": "nijaki"},
    {"polish": "ręka", "english": "hand", "ukrainian": "рука", "part_of_speech": "rzeczownik", "gender": "żeński"},
    {"polish": "noga", "english": "leg", "ukrainian": "нога", "part_of_speech": "rzeczownik", "gender": "żeński"},
]


def seed_words(session: Session) -> None:
    session.add_all([Word(**word_data) for word_data in WORDS_DATA])
    session.commit()
