"""baseline

Revision ID: b4104026fb7f
Revises: 
Create Date: 2026-06-21 13:49:12.117550
"""
from alembic import op
import sqlalchemy as sa


revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('connecteddevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connecteddevice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connecteddevice_ip_address'), ['ip_address'], unique=False)

    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_set', sa.Enum('english', 'ukrainian', name='languageset'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polish', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ukrainian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('rzeczownik', 'czasownik', 'przymiotnik', 'zaimek', 'przyslowek', 'inne', name='partofspeech'), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_part_of_speech'), ['part_of_speech'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_polish'), ['polish'], unique=False)

    op.create_table('endingspracticerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('rzeczownik', 'czasownik', 'przymiotnik', 'zaimek', 'przyslowek', 'inne', name='partofspeech'), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practicerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('language_set', sa.Enum('english', 'ukrainian', name='languageset'), nullable=False),
    sa.Column('direction', sa.Enum('translation', 'writing', 'pronunciation', name='practicedirection'), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practicesentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('rzeczownik', 'czasownik', 'przymiotnik', 'zaimek', 'przyslowek', 'inne', name='partofspeech'), nullable=False),
    sa.Column('sentence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pronoun', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tense', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practicesentence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practicesentence_word_id'), ['word_id'], unique=False)

    op.create_table('usersessionword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['usersession.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word_id')
    )
    op.create_table('verbconjugation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('pronoun', sa.Enum('ja', 'ty', 'on_ona_ono', 'my', 'wy', 'oni_one', name='pronoun'), nullable=False),
    sa.Column('tense', sa.Enum('terazniejszy', 'przeszly', 'przyszly', name='verbtense'), nullable=False),
    sa.Column('conjugated_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'pronoun', 'tense')
    )
    op.create_table('worddeclension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('case', sa.Enum('mianownik', 'dopelniacz', 'celownik', 'biernik', 'narzednik', 'miejscownik', 'wolacz', name='grammaticalcase'), nullable=False),
    sa.Column('gender', sa.Enum('meski', 'zenski', 'nijaki', name='grammaticalgender'), nullable=False),
    sa.Column('number', sa.Enum('singular', 'plural', name='grammaticalnumber'), nullable=False),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'case', 'gender', 'number')
    )
    op.create_table('wordoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('polish', 'english', 'ukrainian', name='wordlanguage'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'language', 'value')
    )
    with op.batch_alter_table('wordoption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wordoption_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordoption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordoption_value'))

    op.drop_table('wordoption')
    op.drop_table('worddeclension')
    op.drop_table('verbconjugation')
    op.drop_table('usersessionword')
    with op.batch_alter_table('practicesentence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practicesentence_word_id'))

    op.drop_table('practicesentence')
    op.drop_table('practicerecord')
    op.drop_table('endingspracticerecord')
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_polish'))
        batch_op.drop_index(batch_op.f('ix_word_part_of_speech'))

    op.drop_table('word')
    op.drop_table('usersession')
    with op.batch_alter_table('connecteddevice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connecteddevice_ip_address'))

    op.drop_table('connecteddevice')
    op.drop_table('appsetting')
    # ### end Alembic commands ###
